.github/workflows/actions.yml, docker/.gitignore, docker/Dockerfile.foxy, docker/Dockerfile.humble, docker/build_docker.bash, docker/entrypoint_foxy.sh, docker/entrypoint_humble.sh, docker/run_docker.bash, docker/setup_xauth.bash, docs/source/setup.rst, docs/source/usage.rst
This PR takes the great updates from @ibrahiminfinite to get display inside a Docker container working without having to run the `xhost` command.
To test:
```
export ROS_DISTRO=foxy #or humble
docker/build_docker.bash
docker/run_docker.bash "ros2 run pyrobosim_ros demo.py"
```
... I additionally added in a little hack that uses a host mounted volume so you don't have to rebuild the colcon workspace across containers by stashing the `install`/`build`/`log` folders in `docker/tmp` on the host. After doing the above, try this:
```
docker/run_docker.bash "ros2 run pyrobosim_ros demo_commands.py"
```
Closes #3
=> Ensure Docker display works without xhost command

docs/source/yaml/world_schema.rst, pyrobosim/examples/test_prm.py, pyrobosim/examples/test_rrt.py, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/core/yaml.py, pyrobosim/pyrobosim/data/test_world.yaml, pyrobosim/pyrobosim/gui/main.py, pyrobosim/pyrobosim/gui/world_canvas.py, pyrobosim/pyrobosim/navigation/prm.py, pyrobosim/pyrobosim/navigation/rrt.py, pyrobosim/pyrobosim/navigation/search_graph.py, pyrobosim/pyrobosim/navigation/trajectory.py, pyrobosim_ros/CMakeLists.txt, pyrobosim_ros/examples/demo.py
This PR adds two main things: some infrastructure to create global vs. local path planners, and then actual sampling-based planner implementations.
* **Global path planners** represent multi-query things such as roadmaps (probabilistic or otherwise) and are properties of the world.
* **Local path planners** represent single-query things such as RRTs and are properties of the robot.
I've arbitrarily picked the robot's local path planner to take precedence if all are specified. Additionally, the existing search graph, which was a hard-coded set of nodes for all rooms/hallways/locations/etc. now still exists as a `SearchGraph` but has a thin wrapper called `SearchGraphPlanner` around it if you want to use it as a planner.
Admittedly, there is still an awkward dependency on the `SearchGraph` …
=> Add global vs. local path planners, with PRM and RRT examples

.github/workflows/actions.yml, docs/source/setup.rst, docs/source/usage/basic_usage.rst, docs/source/usage/tamp.rst, pyrobosim/examples/demo.py, pyrobosim/pyrobosim/core/locations.py, pyrobosim/pyrobosim/core/ros_interface.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/data/pddlstream/domains/04_nav_manip_stream/streams.pddl, pyrobosim_ros/CMakeLists.txt, pyrobosim_ros/examples/demo.py, pyrobosim_ros/examples/demo_commands.py, pyrobosim_ros/examples/demo_pddl_goal_publisher.py, pyrobosim_ros/examples/demo_pddl_planner.py, pyrobosim_ros/examples/demo_pddl_world.py, pyrobosim_ros/launch/demo.py, pyrobosim_ros/launch/demo_commands.py, pyrobosim_ros/launch/demo_pddl.py, pyrobosim_ros/package.xml
This PR aims to switch ROS examples to have parameters specified via launch files.
This will make things easier to run with a single `ros2 launch` command instead of multiple `ros2 run` commands that have to manually match certain arguments to work correctly.
=> Use launch files in ROS examples

pyrobosim/examples/demo_pddl.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/planning/pddlstream/planner.py, pyrobosim/pyrobosim/planning/pddlstream/utils.py, pyrobosim_ros/examples/demo_pddl_planner.py, test/planning/test_pddlstream_nav.py
This PR uses the world model utilities to parse through a planning goal specification so you can simply enter the name of an entity as a string instead of having to manually get the entity object by its name. Basically, the call to `get_entity_by_name()` is stuck inside the planning code.
Before:
```
get = lambda entity : world.get_entity_by_name(entity)
goal_literals = [
("At", get("robot"), get("bedroom")),
("At", get("apple0"), get("table0_tabletop"))
]
```
After:
```
goal_literals = [
("At", "robot", "bedroom"),
("At", "apple0", "table0_tabletop"),
]
```
Closes https://github.com/sea-bass/pyrobosim/issues/23.
=> Find and replace entity names with objects in planning goal specifications

.github/workflows/actions.yml, docker/Dockerfile.foxy, docker/Dockerfile.humble, pyrobosim/pyrobosim/core/world.py, pyrobosim_ros/launch/demo_pddl.py, setup/create_python_env.bash, test/world_model/test_get_entities.py
This should improve the performance of world model lookup functions like `get_object_by_name()` and `get_entity_by_name()` which will be good for repeated lookups.
The benefit comes from switching from linear search over a list of entities to additionally storing them in a dict. There is some memory overhead added, but it shouldn't be that bad.
I also added some unit tests and did a little cleanup.
=> Convert entity-by-name lookup to use a dictionary instead of searching

pyrobosim/examples/demo_pddl.py, test/planning/test_pddlstream_manip.py, test/planning/test_pddlstream_nav.py
Some old syntax carryover from before introducing multi-robot functionality in https://github.com/sea-bass/pyrobosim/pull/28 ... and even more proof that more unit tests are needed.
Closes #34.
=> Fix PDDL standalone demo and unit test syntax

pyrobosim/pyrobosim/utils/pose.py
Found a small issue where a bunch of whitespace was being added when printing the new 3D poses.
=> Fix pose print representation

pyrobosim/pyrobosim/planning/pddlstream/planner.py, test/planning/test_pddlstream_manip.py
This PR adds a `max_attempts` argument to the `PDDLStreamPlanner.plan()` method to allow retries if task and motion planning fails.
While this was originally intended to address a flaky test which sometimes fails, I realized this utility is generally useful.
=> Add max attempts to PDDLStream planning

pyrobosim/pyrobosim/core/ros_interface.py
This fixes the threading issue mentioned here:  https://github.com/sea-bass/tiago_behavior_demos/pull/7
I haven't fully tested it with the different pyrobosim executables yet.
Inspiration drawn from this example:  https://github.com/ros2/examples/blob/fee0b7f266e92c4a9f3f6ec760472ab8f23b80e1/rclpy/executors/examples_rclpy_executors/callback_group.py#L57
=> Use a multi-threaded executor and CB groups in the ROS interface

pyrobosim/pyrobosim/planning/pddlstream/planner.py, test/planning/test_pddlstream_manip.py
In https://github.com/sea-bass/pyrobosim/pull/40, we added some logic to retry plans; however, the check needed to be done on the plan which is only the first element of the solution tuple.
=> Fix PDDLStream planner retry logic

pyrobosim/pyrobosim/utils/pose.py
=> Add matrix getters to Pose class

pyrobosim/pyrobosim/core/yaml.py, pyrobosim/pyrobosim/navigation/trajectory.py
For some reason, I had written a `get_value_or()` function to get data from a dict, but fall back to a default value if that key doesn't exist... when actually Python dicts already have a `get()` method that does just this.
I also found a small issue in another file while testing in Python 3.8 so sneaking in that fix.
=> Use dict get() method in YAML loading utilities

pyrobosim/examples/demo_grasping.py, pyrobosim/pyrobosim/core/objects.py, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/manipulation/__init__.py, pyrobosim/pyrobosim/manipulation/grasping.py, pyrobosim/pyrobosim/utils/polygon.py, pyrobosim/pyrobosim/utils/pose.py, test/manipulation/test_grasping.py, test/utils/test_polygon_utils.py
This PR creates a grasp generation pipeline that takes in the gripper / object dimensions, plus the robot pose relative to the object, and generates a set of feasible grasps.
For now, we'll assume all grasps will point towards the center and axis-aligned with a cuboid object.
The goal for this PR is:
* Given an object's geometry (2D polygon footprint + height), fit a minimum-area cuboid to it
* Given the cuboid and the robot's pose, return a set of valid grasps
In a follow-on PR, this pipeline will be linked to an example showing a next level of TAMP fidelity, where the planner can only pick up objects given feasible grasp locations sampled from this pipeline.
Here is a visualization of the grasp generation. You can run this with:
```
cd /path/to/pyrobosim
python …
```
=> Grasp generation tools

docs/source/yaml/world_schema.rst, pyrobosim/examples/demo.py, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/yaml.py, pyrobosim/pyrobosim/data/pddlstream_simple_world.yaml, pyrobosim/pyrobosim/data/test_world.yaml, pyrobosim/pyrobosim/data/test_world_multirobot.yaml, pyrobosim/pyrobosim/gui/world_canvas.py
This PR builds on https://github.com/sea-bass/pyrobosim/pull/44 and adds the ability to configure a grasp generator for a robot, as well as use it as part of a robot's `pick_object()` action with some basic logic.
The idea is that for a "real" task and motion planner, the grasp generator will be used elsewhere and the pose will directly be passed into the action interface.
Makes progress towards #45.
=> Use grasp generator in robot model and `pick_object()` action

pyrobosim_ros/examples/demo_pddl_goal_publisher.py, pyrobosim_ros/examples/demo_pddl_planner.py
Detect Ctrl+C and quit the while loop gracefully. Also, added a sleep to one loop to reduce CPU usage.
=> Loop logic cleanup

pyrobosim/examples/demo.py, pyrobosim/examples/demo_pddl.py, pyrobosim/pyrobosim/gui/main.py, pyrobosim_ros/examples/demo.py, pyrobosim_ros/examples/demo_pddl_world.py, setup/create_python_env.bash
Also helps address #64.
Now any program that uses the GUI will terminate correctly when Ctrl+C is pressed. I also realized I was duplicating code to start the GUI and moved it to a utility.
=> Enable Ctrl+C to stop the GUI

pyrobosim_ros/examples/demo_pddl_planner.py, setup/create_python_env.bash
Use a timer as suggested here:
https://answers.ros.org/question/356686/python-not-able-to-echo-ros2-topics-published-on-thread/
The cause of the deadlock had something to do with rclpy threading intricacies.
=> Refactor demo_pddl_planner.py to avoid deadlock

pyrobosim/pyrobosim/gui/world_canvas.py, pyrobosim/setup.py
This addresses the matplotlib issue we found related to https://github.com/matplotlib/matplotlib/issues/22093, without having to pin down to an older version.
I tried with version 3.4 and 3.7.1 (the latest available right now).
Try it out? Best way is to remove any virtual environment you may have, or at least manually upgrade your matplotlib to the latest.
=> Fix matplotlib artist removal for later versions

docs/source/yaml/location_schema.rst, docs/source/yaml/world_schema.rst, pyrobosim/examples/demo.py, pyrobosim/examples/test_world.py, pyrobosim/pyrobosim/core/hallway.py, pyrobosim/pyrobosim/core/locations.py, pyrobosim/pyrobosim/core/objects.py, pyrobosim/pyrobosim/core/room.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/core/yaml_utils.py, pyrobosim/pyrobosim/data/pddlstream_simple_world.yaml, pyrobosim/pyrobosim/data/test_world.yaml, pyrobosim/pyrobosim/data/test_world_multirobot.yaml, pyrobosim/pyrobosim/planning/__init__.py, pyrobosim/pyrobosim/planning/pddlstream/planner.py, pyrobosim/pyrobosim/utils/general.py, pyrobosim_ros/examples/demo.py, pytest.ini, test/planning/test_pddlstream_manip.py, test/planning/test_pddlstream_nav.py, test/world_model/test_get_entities.py, test/world_model/test_hallway.py, test/world_model/test_location.py, test/world_model/test_locations.py, test/world_model/test_objects.py, test/world_model/test_room.py
This PR takes advantage of Python keyword arguments (`**kwargs`) to unify the interface to world entities, such as Rooms, Hallways, etc.
This way, the same arguments used to create an entity, for example a `Room` object, can be reused directly in world methods such as `add_room()`, but also in the YAML parsers.
There are breaking changes because everything now required named arguments, but I think now there is more consistency, less copy-pasting of code, and actually more functionality. The only reason this PR has added lines of code is because of all the unit tests I created in doing this refactoring.
Closes #77
=> Unify world entity creation arguments

docker-compose.yaml
This small change makes it so you don't need to run `xhost + local:docker` before launching pyrobosim in the Docker container.
To test:
```
xhost - local:docker  # (or restart your machine)
docker compose build
docker compose up demo
```
Does the GUI appear?
=> Mount Xauthority file to Docker container

pyrobosim/pyrobosim/navigation/trajectory.py
Found a small bug that was making the trajectory execution angular velocity limiting be super slow.
Turns out the check always assumed that the robot was at zero yaw, so we kept throttling the angular speed for no reason.
To test:
* Check out `main` and run the demo with an A* planner with diagonal moves allowed. Navigate to `counter0` and watch the robot struggle to follow the diagonal waypoints.
* Check out this branch and try the same
=> Fix angular velocity limiting in trajectory executor

.github/workflows/tests.yml, docker/Dockerfile, setup/create_python_env.bash
CI started failing because of some `pytest` error, and I found it's specific to the version of a dependency of `pytest-html`, namely `py 1.10.0`.
For now I've made avoiding this version explicit in the relevant `pip3 install` commands...
=> Fix pytest errors in 22.04 Docker images

.github/workflows/tests.yml, docs/source/setup.rst, setup/source_pyrobosim.bash
Since ROS 2 Foxy is now EOL, I will drop support and add ROS 2 Iron.
You can try installing `pyrobosim` with ROS 2 Iron locally, or build the Docker image with:
```
export ROS_DISTRO=iron
docker compose build
```
=> Remove ROS 2 Foxy support, add Iron support

pyrobosim_ros/examples/demo_commands.py
There was an old mention of a "robby" robot in the ROS demo file, which was renamed to "robot2".
To test:
* Local: `ros2 launch pyrobosim_ros demo_commands_multirobot.launch.py`
* Docker: `docker compose up demo_multirobot_ros`
=> Fix robot name in multirobot ROS demo

pyrobosim/examples/demo.py, pyrobosim/examples/demo_pddl.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/data/pddlstream_simple_world.yaml, pyrobosim/pyrobosim/data/test_world.yaml, pyrobosim/pyrobosim/data/test_world_multirobot.yaml, pyrobosim/pyrobosim/planning/pddlstream/default_mappings.py, pyrobosim/pyrobosim/planning/pddlstream/primitives.py, pyrobosim_ros/examples/demo.py, pyrobosim_ros/examples/demo_pddl_planner.py, pyrobosim_ros/launch/demo_pddl.launch.py, test/planning/test_pddlstream_manip.py, test/system/test_system_world.yaml
I recently did a few demos where the PDDLStream examples `04_nav_manip_stream` and `05_nav_grasp_stream` were failing almost all the time. Did some tuning here to make things work better and look nicer.
* Reduced the object radius from 0.05 to 0.0375
* Reduced the max planning time and search-sample ratio in PDDLStream + added retries
* Removed padding option to PDDLStream object placement streams, as the calls to inflate the polygons each function call were unnecessary
* Tuned RRT to have higher connection distances and rewire radius so the paths were less "jagged" (more cosmetic than anything)
To test, run these a bunch of times:
```
python pyrobosim/examples/demo_pddl.py --example 04_nav_manip_stream
python pyrobosim/examples/demo_pddl.py --example 05_nav_grasp_stream
```
=> Tune parameters for complex PDDLStream examples

pyrobosim/examples/demo_astar.py, pyrobosim/pyrobosim/navigation/a_star.py, test/navigation/test_astar.py
The mechanism to compress the A* path was missing in the implementation.
=> Add missing path compression option in A* planner

pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/utils/general.py, pyrobosim/pyrobosim/utils/knowledge.py
This PR fixes circular imports in the knowledge utilities by importing from the core modules only in the functions that require it.
It also ensures that Location and Object metadata is always set to a blank dictionary even when nothing has been specified, to prevent runtime errors.
Closes https://github.com/sea-bass/pyrobosim/issues/122
=> Fix circular imports in knowledge utilities

.github/workflows/tests.yml, CONTRIBUTING.md, docker-compose.yaml, pyrobosim_ros/CMakeLists.txt, pyrobosim_ros/package.xml, pyrobosim_ros/pyrobosim_ros/ros_conversions.py, pyrobosim_ros/test/CMakeLists.txt, pyrobosim_ros/test/test_ros_conversions.py, test/run_tests.bash
This PR adds unit tests to the `pyrobosim_ros` package for the conversion utilities.
It also necessarily stands up infrastructure to run these tests from ROS package using `colcon test`, and therefore adds an extra argument to the `test/run_tests.bash` script for ROS workflows.
Closes https://github.com/sea-bass/pyrobosim/issues/105
=> Add basic colcon tests to `pyrobosim_ros` package

pyrobosim/pyrobosim/utils/pose.py
Fixes #127 - Weird issue with rel_tol=1e-09 being Pose instead of float?
=> Adds Pose equivalency functions

pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/data/pddlstream_simple_world.yaml, pyrobosim/pyrobosim/gui/world_canvas.py, test/planning/test_pddlstream_manip.py, test/planning/test_pddlstream_nav.py
Found a small bug while testing before a presentation.
It seems like by removing some class attributes in a recent PR, sending an action to the GUI with an already-planned path was discarding the path and trying to plan again.
=> Add nav action path to GUI nav trigger signal

pyrobosim/pyrobosim/navigation/prm.py, pyrobosim/pyrobosim/navigation/world_graph.py, pyrobosim/pyrobosim/utils/search_graph.py, test/utils/test_search_graph.py
This PR adds unit tests for the `SearchGraph` class, which necessarily also tests other associated classes like `Node`, `Edge`, and `SearchGraphPlanner`.
Also found some fixes along the way -- the main one being that we weren't returning a `Path` object uniformly when calling out to a-star, so this logic had to be absorbed in the planners themselves.
Closes https://github.com/sea-bass/pyrobosim/issues/103
=> Add unit tests for search graph

pyrobosim/pyrobosim/navigation/planner_base.py, pyrobosim/pyrobosim/planning/pddlstream/primitives.py, pyrobosim/pyrobosim/utils/motion.py, pyrobosim/pyrobosim/utils/pose.py, pyrobosim_ros/test/test_ros_conversions.py, test/planning/test_task_objects.py, test/test_dependencies.py, test/utils/test_knowledge_utils.py, test/utils/test_motion_utils.py, test/utils/test_pose_utils.py
This PR adds some basic unit tests for the task and motion planning object representations. These classes are simple, so not much to be done here.
Closes https://github.com/sea-bass/pyrobosim/issues/96
=> Add unit tests for `TaskPlan` and `TaskAction` objects

pyrobosim/pyrobosim/core/locations.py, pyrobosim/pyrobosim/core/objects.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/utils/general.py, test/core/test_world.py, test/core/test_yaml_utils.py
When writing tests, I noticed that there were some cases in `World.add_location()` and `World.add_object()` that would lead to uncaught exceptions. This was specifically:
* Missing the `parent` input
* Using a nonexistent category and thereby getting no metadata
I've added some guards to that, as well as unit tests in both the world creation and YAML loading tests.
=> Handle missing parent and invalid categories when adding locations and objects

.github/workflows/tests.yml, docker-compose.yaml
Instead of running a monolithic `docker compose` command, this PR breaks out the actions into build and test.
Hopefully this paves the way for being smarter about caching/breaking out the actions further to minimize CI times.
=> Split out CI jobs

test/run_tests.bash
Found an issue in the test script, where the coverage was meant to point at the source directory and not the test directory.
OLD:
NEW:
=> Fix coverage base folder

docs/source/usage/index.rst, docs/source/usage/robot_dynamics.rst, docs/source/yaml/world_schema.rst, pyrobosim/examples/demo_dynamics.py, pyrobosim/pyrobosim/core/__init__.py, pyrobosim/pyrobosim/core/dynamics.py, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/core/yaml_utils.py, pyrobosim/pyrobosim/data/test_world.yaml, pyrobosim/pyrobosim/gui/main.py, pyrobosim/pyrobosim/gui/world_canvas.py, pyrobosim/pyrobosim/planning/pddlstream/utils.py, pyrobosim/pyrobosim/utils/dynamics.py, pyrobosim/pyrobosim/utils/knowledge.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py, test/core/test_dynamics.py, test/core/test_robot.py, test/core/test_world.py, test/core/test_yaml_utils.py, test/utils/test_knowledge_utils.py
This PR adds simple 2D robot dynamics to core (non-ROS) pyrobosim.
Partially closes https://github.com/sea-bass/pyrobosim/issues/148
=> Simulate simple 2D robot dynamics

docs/source/usage/robot_dynamics.rst, pyrobosim/pyrobosim/core/world.py, pyrobosim_msgs/package.xml, pyrobosim_ros/CMakeLists.txt, pyrobosim_ros/examples/demo.py, pyrobosim_ros/examples/demo_velocity_publisher.py, pyrobosim_ros/launch/demo.launch.py, pyrobosim_ros/package.xml, pyrobosim_ros/pyrobosim_ros/ros_conversions.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py, pyrobosim_ros/test/test_ros_conversions.py
This PR follows from #151 and adds the ROS wrapper around robot dynamics.
Now, each spawned robot will additionally have a `<robot_name>/cmd_vel` subscriber where you can send it `geometry_msgs/Twist` commands like with most mobile bases in ROS.
Because of ROS Publishing timing, we also need a command latching and ramp-down time to be defined.
Closes #148
=> Add robot velocity command ROS subscribers

.github/workflows/tests.yml
This seems to be needed to allow PRs to generate the coverage message?
=> Add PR write permissions to tests CI job

docker-compose.yaml
It's a minor change, but otherwise you have to wait ~10s for your containers to shutdown when you kill them (or smash `ctrl-c`).
=> Set init for compose services

.github/workflows/tests.yml, docker-compose.yaml, docker/Dockerfile, test/run_tests.bash
Will allow us to take advantage of docker's cache for pddl builds in the base python tests, finishing off the @ibrahiminfinite's request from https://github.com/sea-bass/pyrobosim/issues/85.
I added another stage to the Dockerfile for a very, very basic non-ros build. This should keep the docker build cache until you blow up the dependencies (note this can happen when apt or pip packages get updated... so it's not bulletproof). The tests are now run in the built container.
Renamed the ROS images accordingly.
Build times for a cached build:
I fully recognize that I have a problem...
=> Containerize the non-ros testing pipeline

pyrobosim/pyrobosim/core/world.py, test/python_test_requirements.txt
Somehow the recent release of pytest 8.1.1 changed things so that passing an exception to `warnings.warn()` yielded an error. Converting the exception to a string before passing it in seems to solve the issue.
In addition to that, seems like there are issues with ROS tests as shown here: https://github.com/ros2/launch/issues/765. Since the PR to fix it only went into rolling and it's being debated whether it will be backported, may as well just pin the pytest version for now
=> Pin pytest below 8.1.0 and fix warnings when creating entities with invalid categories

pyrobosim/examples/demo_pddl.py, pyrobosim/pyrobosim/planning/__init__.py, pyrobosim/pyrobosim/planning/pddlstream/__init__.py, pyrobosim_ros/examples/demo_pddl_planner.py, setup/setup_pddlstream.bash, test/planning/test_pddlstream_manip.py, test/planning/test_pddlstream_nav.py, test/test_dependencies.py, test/test_pyrobosim.py
This PR makes PDDLStream optional for tests, and also updates to the main PDDLStream repo.
It also shuffles around some of the import code so that users get a more readable error message when they try to import the PDDLStream planner and don't have the module available.
=> Do not require PDDLStream for tests, switch to main repo

docker/Dockerfile
Turns out after Ubuntu 23.04, Canonical got way more strict about using system Python to install stuff... https://www.reddit.com/r/Python/comments/1338oge/you_cant_use_pip_on_ubuntu_2304_anymore/
This is why the recent breakages came in, as in https://github.com/sea-bass/pyrobosim/actions/runs/8841625181, since `runs-on: ubuntu-latest` now points to Ubuntu 24.04.
I'm going to do the "band-aid" fix for now and worry about something more principled once we make the move officially to Ubuntu 24.04 / ROS 2 Jazzy. Will likely involve using a virtual environment in the Dockerfiles as well, as we already do for local setup instructions.
=> Fix pip install in Ubuntu 24.04 Dockerfile

.dockerignore, .github/workflows/tests.yml, docker-compose.yaml, docker/Dockerfile, docker/entrypoint.sh, docs/source/setup.rst, pyrobosim_msgs/CMakeLists.txt, pyrobosim_ros/CMakeLists.txt, setup/create_python_env.bash, setup/generate_docs.bash, setup/setup_pddlstream.bash, setup/source_pyrobosim.bash, test/python_test_requirements.txt, test/run_tests.bash
This PR switches to use [ROS (not OSRF) Docker images](https://hub.docker.com/_/ros/) and also adds Jazzy support now that it's out.
=> Support ROS 2 Jazzy / Ubuntu 24.04

docs/source/usage/basic_usage.rst, docs/source/usage/multirobot.rst, pyrobosim/examples/demo_pddl.py, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/planning/actions.py, pyrobosim_msgs/CMakeLists.txt, pyrobosim_msgs/action/ExecuteTaskAction.action, pyrobosim_msgs/action/ExecuteTaskPlan.action, pyrobosim_msgs/package.xml, pyrobosim_ros/examples/demo.py, pyrobosim_ros/examples/demo_commands.py, pyrobosim_ros/examples/demo_pddl_goal_publisher.py, pyrobosim_ros/examples/demo_pddl_planner.py, pyrobosim_ros/examples/demo_pddl_world.py, pyrobosim_ros/examples/demo_velocity_publisher.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py, test/core/test_robot.py, test/planning/test_pddlstream_manip.py, test/planning/test_pddlstream_nav.py
Instead of unilaterally sending topics to the simulator ROS interface to execute actions or task plans, this PR uses a proper action interface.
There are probably more things to implement in this fashion in the example, as well as more state tracking (e.g., publishing feedback), but we'll start with this.
Closes #172
=> Use ROS actions to execute actions and task plans

pyrobosim/setup.py
Until [adjustText](https://github.com/Phlya/adjustText) releases a new version with the fixes, it will not be compatible with NumPy 2.0.0. So pinning for now.
=> Pin NumPy below 2.0.0

docker/Dockerfile, pyrobosim/setup.py, setup/create_python_env.bash
This reverts commit 3ee93eefe4da2cf505af2b99360842d163848357.
`adjustText` came out with a 1.2.0 version which is compatible with NumPy 2.0.0, so we are good.
=> Unpin NumPy and do not upgrade pip in scripts and CI

pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/gui/world_canvas.py, pyrobosim/pyrobosim/navigation/execution.py, setup/setup_pyrobosim.bash, test/core/test_robot.py
Previously, non-blocking navigation actions were returning `True` as the path planning was simply delegated but its status was never checked.
This adds a new state to the robot for us to be able to check navigation status, and also adds more checks for cases where path planning fails before it starts executing (which was also not being validated).
=> Allow path planning failures to fail navigate actions

pyrobosim/pyrobosim/core/robot.py
=> Small fix to nav failure state tracking

pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/gui/main.py, pyrobosim/pyrobosim/gui/world_canvas.py
I was originally trying to get rid of these occasional prints:
```
QBasicTimer::stop: Failed. Possibly trying to stop from a different thread
```
... but to no avail. However, it did clean some stuff up. Maybe?
=> Cleanup navigation display and execution in GUI

pyrobosim/pyrobosim/navigation/prm.py, pyrobosim/pyrobosim/navigation/rrt.py, test/navigation/test_prm.py, test/navigation/test_rrt.py
Added tests for PRM and RRT planner, fixing a few small things along the way.
Notably, I found a very easy speedup to the PRM generation by not doing all the neighbor connection AFTER sampling; rather, doing it during sampling. Silly me.
Closes https://github.com/sea-bass/pyrobosim/issues/188
=> Flesh out tests for RRT and PRM planner

docs/source/usage/robot_actions.rst, pyrobosim/pyrobosim/core/hallway.py, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/data/pddlstream_simple_world.yaml, pyrobosim/pyrobosim/data/test_world.yaml, pyrobosim/pyrobosim/data/test_world_multirobot.yaml, pyrobosim/pyrobosim/gui/main.py, pyrobosim/pyrobosim/gui/world_canvas.py, pyrobosim/pyrobosim/navigation/rrt.py, pyrobosim/pyrobosim/planning/actions.py, pyrobosim/pyrobosim/utils/knowledge.py, test/core/test_hallway.py, test/core/test_robot.py, test/utils/test_knowledge_utils.py
This PR adds the ability for a robot to open/close a hallway when navigating to its doorways (which is also a new feature).
You can also lock and unlock the hallway. When locked, open/close will not work so the robot's actions will fail.
Known limitations:
* Occupancy grid based planners like A* will still navigate through closed hallways unless the occupancy grid is explicitly regenerated.
* When the robot navigates to a hallway, it picks the closest endpoint by direct distance, which may lead to roundabout paths in certain cases.
=> Add hallway open and close capabilities

pyrobosim/pyrobosim/core/locations.py
Fixes a small bug found while testing.
Apparently location-level nav poses were always defaulting to the pose of the parent instead of the nav pose. We didn't see this with the "table" because the location itself is rotated in our examples.
This was not the case for object spawns, which was correct.
=> Fix yaw setting in location nav poses

pyrobosim/pyrobosim/core/hallway.py, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/gui/main.py, pyrobosim/pyrobosim/gui/world_canvas.py, test/core/test_robot.py, test/system/test_system.py, test/system/test_system_world.yaml
This PR reduces duplication in the nav code that existed in both the GUI and the robot. Now it's all delegated to the robot, which has a `navigate()` method that contains `find_path()` and `follow_path()`.
Additionally, the `target_location` argument of the nav functions is gone, meaning it does not need to be specified a priori; the `World.get_location_from_pose()` method has been extended to also extract object spawn and hallway information.
I also found a few other UI simplifications along the way...
=> Unify navigation code and automatically extract robot location

docs/source/usage/robot_actions.rst, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/planning/actions.py, pyrobosim_msgs/CMakeLists.txt, pyrobosim_msgs/msg/ActionExecutionOptions.msg, pyrobosim_msgs/msg/TaskAction.msg, pyrobosim_ros/examples/demo_commands.py, pyrobosim_ros/launch/demo_commands.launch.py, pyrobosim_ros/pyrobosim_ros/ros_conversions.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py, pyrobosim_ros/test/test_ros_conversions.py, test/core/test_robot.py, test/planning/test_task_objects.py
This PR allows simulating action delays and failures, including a settable RNG seed for reproducibility.
Right now, this works for both the Python API and ROS interface, but not directly from the GUI.
Closes #177
=> Simulate delays and failures when executing actions

docs/source/usage/index.rst, pyrobosim/examples/demo.py, pyrobosim/pyrobosim/core/gazebo.py, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/core/yaml_utils.py, pyrobosim/pyrobosim/data/pddlstream_simple_world.yaml, pyrobosim/pyrobosim/data/test_world.yaml, pyrobosim/pyrobosim/gui/__init__.py, pyrobosim/pyrobosim/navigation/execution.py, pyrobosim/pyrobosim/utils/motion.py, pyrobosim/pyrobosim/utils/pose.py, pyrobosim/pyrobosim/utils/trajectory.py, test/core/test_robot.py, test/system/test_system.py, test/system/test_system_world.yaml, test/utils/test_motion_utils.py, test/utils/test_pose_utils.py
This PR adds an option for path executors to spawn a new thread and collision-check the remaining path to be executed.
I also did a drive-by fix of #207 :)
Closes #191 
Closes #207
=> Add path execution validation and abort

pyrobosim/pyrobosim/core/robot.py, pyrobosim_ros/examples/demo_commands.py, pyrobosim_ros/launch/demo_commands.launch.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py, test/core/test_robot.py
This PR allows canceling running actions and task plans, both with the Python API and ROS interface.
This is not supported from the GUI in this PR.
Closes #203
=> Allow canceling actions and plans

docs/source/concepts.rst, docs/source/setup.rst, docs/source/usage/basic_usage.rst, docs/source/usage/geometry_conventions.rst, docs/source/usage/path_planners.rst, docs/source/usage/robot_actions.rst, docs/source/usage/tamp.rst, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/navigation/execution.py, pyrobosim/pyrobosim/planning/actions.py, pyrobosim_msgs/CMakeLists.txt, pyrobosim_msgs/action/ExecuteTaskAction.action, pyrobosim_msgs/action/ExecuteTaskPlan.action, pyrobosim_msgs/msg/ExecutionResult.msg, pyrobosim_ros/pyrobosim_ros/ros_conversions.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py, pyrobosim_ros/test/test_ros_conversions.py, test/core/test_hallway.py, test/core/test_robot.py, test/system/test_system.py
This PR switches action/plan execution from returning a binary success/failure to using a full `ExecutionStatus` object with different status codes and optional messages.
The ROS interface is also affected by the same, adding a new `pyrobosim_msgs.msg.ExecutionStatus` message type. This is a field in the result of both action interfaces.
Closes #185
=> Add execution status to actions and plans

pyrobosim_msgs/CMakeLists.txt, pyrobosim_msgs/srv/RequestWorldState.srv, pyrobosim_msgs/srv/SetLocationState.srv, pyrobosim_ros/pyrobosim_ros/ros_interface.py
This PR adds a new `/set_location_state` service to the ROS interface to open, close, lock, and unlock locations.
Right now, only Hallways are supported, but more will eventually be tracked by #208.
To test, you can run commands like these:
```
ros2 launch pyrobosim_ros demo.launch.py
ros2 service call /set_location_state pyrobosim_msgs/srv/SetLocationState \
"{location_name: hall_kitchen_bathroom, open: false, lock: false}"
```
Closes #213
=> Add ROS service to set location state

docs/source/usage/robot_actions.rst, docs/source/yaml/location_schema.rst, docs/source/yaml/world_schema.rst, pyrobosim/pyrobosim/core/locations.py, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/data/pddlstream_simple_world.yaml, pyrobosim/pyrobosim/data/test_world.yaml, pyrobosim/pyrobosim/data/test_world_multirobot.yaml, pyrobosim/pyrobosim/gui/main.py, pyrobosim/pyrobosim/gui/world_canvas.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py, test/core/test_hallway.py, test/core/test_locations.py, test/core/test_robot.py, test/core/test_world.py, test/system/test_system.py, test/system/test_system_world.yaml
This PR extends the Open/Close actions from just Hallway objects to also Location objects.
I don't like how much duplication there is between these 2 types of objects... but I'm inclined to handle that later.
https://github.com/user-attachments/assets/79438f20-5d5a-4ad5-b804-ec7476cf1208
Closes #208
=> Extend Open/Close actions to storage locations

pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/gui/main.py, pyrobosim/pyrobosim/gui/world_canvas.py, pyrobosim/pyrobosim/navigation/path_planner.py, pyrobosim/pyrobosim/navigation/planner_base.py, pyrobosim/pyrobosim/utils/knowledge.py, test/system/test_system.py, test/utils/test_knowledge_utils.py
I realized when running the PDDLStream examples that the navigation path was not being displayed if the path was already given (i.e., planning doesn't happen at the time of executing the "navigate" action).
This probably was a problem introduced in https://github.com/sea-bass/pyrobosim/pull/202
This PR fixes that.
---
I also moved some query resolution / knowledge code that was in the UI to the regular robot actions, uncovering some kinks in those utilities, and fixed those as well.
=> Show path in GUI when the path is given beforehand + unify query to entity support in GUI vs. non-GUI actions

pyrobosim/pyrobosim/core/robot.py, pyrobosim_ros/test/test_ros_interface.py, setup/setup_pyrobosim.bash
Fixes an issue highlighted by @oberacda (thank you!), in which path planning failures don't correctly pipe their status all the way up the ROS interface.
Also added tests for this case.
Closes https://github.com/sea-bass/pyrobosim/issues/229
=> Handle path planning failures correctly in action interface

pyrobosim/pyrobosim/core/robot.py, pyrobosim_msgs/srv/RequestWorldState.srv, pyrobosim_ros/pyrobosim_ros/ros_interface.py, pyrobosim_ros/test/test_ros_interface.py
Another small feature request from @oberacda for the ROS interface.
Now the `RequestWorldState` service can optionally accept a robot name to get its local observations. Right now, this only pertains to objects that the robot has not seen, if it has partial observability enabled..
=> Support getting local robot observations in world state ROS service

docs/source/usage/robot_actions.rst, docs/source/yaml/location_schema.rst, docs/source/yaml/world_schema.rst, pyrobosim/pyrobosim/core/locations.py, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/yaml_utils.py, pyrobosim/pyrobosim/data/example_location_data.yaml, pyrobosim/pyrobosim/data/test_world_multirobot.yaml, pyrobosim/pyrobosim/gui/main.py, pyrobosim/pyrobosim/gui/world_canvas.py, pyrobosim/pyrobosim/navigation/execution.py, pyrobosim/pyrobosim/planning/actions.py, pyrobosim_msgs/msg/RobotState.msg, pyrobosim_ros/pyrobosim_ros/ros_interface.py, pyrobosim_ros/test/test_ros_interface.py, test/core/test_robot.py, test/core/test_yaml_utils.py
This PR adds battery level to robots, as well as the option to simulate battery usage per action.
As a side effect, this PR also correctly applies action execution options from manually interacting with the GUI, which was not previously available.
Closes https://github.com/sea-bass/pyrobosim/issues/230
=> Simulate robot battery usage and charging

docs/source/usage/tamp.rst, pyrobosim/examples/demo_pddl.py, pyrobosim/pyrobosim/core/hallway.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/data/pddlstream/domains/01_simple/domain.pddl, pyrobosim/pyrobosim/data/pddlstream/domains/02_derived/domain.pddl, pyrobosim/pyrobosim/data/pddlstream/domains/03_nav_stream/domain.pddl, pyrobosim/pyrobosim/data/pddlstream/domains/04_nav_manip_stream/domain.pddl, pyrobosim/pyrobosim/data/pddlstream/domains/05_nav_grasp_stream/domain.pddl, pyrobosim/pyrobosim/data/pddlstream/domains/06_open_close_detect/domain.pddl, pyrobosim/pyrobosim/data/pddlstream/domains/06_open_close_detect/streams.pddl, pyrobosim/pyrobosim/planning/actions.py, pyrobosim/pyrobosim/planning/pddlstream/default_mappings.py, pyrobosim/pyrobosim/planning/pddlstream/primitives.py, pyrobosim/pyrobosim/planning/pddlstream/utils.py, pyrobosim_msgs/msg/LocationState.msg, pyrobosim_ros/examples/demo_pddl_goal_publisher.py, pyrobosim_ros/examples/demo_pddl_planner.py, pyrobosim_ros/launch/demo_pddl.launch.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py, test/planning/test_task_objects.py
This PR includes some of our new actions (open, close, detect) in the PDDL domains.
You can test this with the new `06_open_close_detect` planning domain:
* Core: `python3 pyrobosim/examples/demo_pddl.py  --example 06_open_close_detect --verbose`
* ROS: `ros2 launch pyrobosim_ros demo_pddl.launch.py example:=06_open_close_detect`
Note that this has some limitations:
* Hallway state is not communicated across the ROS interface (but location state does!)
* Open/locked state pertains to entire locations, but the PDDL domains deal in individual object spawns. As such, you may not get things working exactly as desired with openable locations that have multiple object spawns.
* At the start of planning, we assume no locations have been observed (which is not true in subsequent plans).
* Detect …
=> Enable Open, Close, and Detect actions in PDDL capabilities

pyrobosim/setup.py
Based on https://github.com/sea-bass/pyrobosim/issues/236, I am putting a minimum version on this package.
I've confirmed that this minimum version is available in Python 3.8, so it's not overly restrictive.
=> Require PySide6 6.4.0 or greater

pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/gui/main.py, pyrobosim/pyrobosim/gui/world_canvas.py, pyrobosim_msgs/CMakeLists.txt, pyrobosim_msgs/action/FollowPath.action, pyrobosim_msgs/action/PlanPath.action, pyrobosim_ros/pyrobosim_ros/ros_interface.py, pyrobosim_ros/test/test_ros_interface.py, test/core/test_robot.py
This PR adds new action servers that perform path planning and following for individual robots.
* `<robot_name>/plan_path` performs path planning with the `pyrobosim_msgs.action.PlanPath` action.
* This can accept either a target location name (string) or pose. 
* `<robot_name>/follow_path` perform path following with the `pyrobosim_msgs.action.FollowPath` action.
* This accepts a path which you can directly grab from the result of the path planning action.
* This action can be canceled if you want to abort path execution.
I was also finally able to remove unnecessary threading/blocking arguments to the `Robot.navigate()` and `Robot.follow_path()` methods.
Closes https://github.com/sea-bass/pyrobosim/issues/197
=> Add specialized ROS action servers for path planning and following

pyrobosim/pyrobosim/gui/main.py, pyrobosim/pyrobosim/gui/world_canvas.py
- Refactored `show()` by creating `show_rooms()` function https://github.com/sea-bass/pyrobosim/blob/ea926bbdf736f5dbc2537dcc0d35789bb54e2d86/pyrobosim/pyrobosim/gui/world_canvas.py#L305
- Implemented `show_rooms()` similar `show_hallways()` https://github.com/sea-bass/pyrobosim/blob/ea926bbdf736f5dbc2537dcc0d35789bb54e2d86/pyrobosim/pyrobosim/gui/world_canvas.py#L223
- This helped me create a new function `toggle_collision_polygons()` which calls `show()` and `show_rooms()` to redraw rooms and hallways with/without collision polygons upon toggling a checkbox
- Added a checkbox as part of action buttons https://github.com/sea-bass/pyrobosim/blob/ea926bbdf736f5dbc2537dcc0d35789bb54e2d86/pyrobosim/pyrobosim/gui/main.py#L135
- Pull request shows 2 contributors because I had some trouble …
=>  Add UI button to toggle collision polygon display (issue #200) 

pyrobosim/pyrobosim/core/robot.py
Small bug fix when sending a ROS navigation action goal without the `target_location` set.
=> Gracefully exit navigation action when target location is not specified

pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/yaml_utils.py, pyrobosim/pyrobosim/gui/main.py, pyrobosim/test/core/test_robot.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py
This PR allows resetting the path planner from the UI.
This means that now if you close a hallway from the UI, you can reset the planner for a robot with PRM/A* and then replan without going right through the door.
Thanks to @muhidabid for setting the foundation with his "Cancel Action" button, I could just copy-paste exactly what he did :)
=> Add Reset Path Planner UI button

pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/navigation/rrt.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py
When path planning fails, most planners return a `Path` with 0 poses instead of `None`.
So this should also be counted as a failure, in contrast with a trivial path which has 2 identical start and goal points.
=> Count paths with zero poses as path planning failures

pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/gui/main.py, pyrobosim/test/core/test_hallway.py, pyrobosim/test/core/test_robot.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py
This PR allows opening/closing storage locations and hallways from the UI globally -- meaning you can select `"world"` from the drop-down menu and then open/close whatever location is set in the goal textbox.
I also unified the `open/close/lock/unlock` methods for hallways and locations and removed a lot of copypasta, as well as some bits of unreachable code.
=> Allow opening and closing locations globally from GUI

pyrobosim/pyrobosim/core/world.py
This kind of started as a hack, but I'm really warming up to it in that I can't think of anything better that won't take some serious recursive / geometric analysis...
I recently ran into a "feature" with navigating to a hallway. Take this world:
If you are navigating to the hallway between `office` and `closet`, the default heuristic will tell the robot to go to the left side of the hallway because it's nearer to the current robot pose as the crow flies. But as you see, path planning will fail.
This PR will look for "landlocked" hallways as described above by checking that there is at least one open hallway on either room, or that the robot isn't inside that room. If there isn't (like in the case of `closet` in the screenshot above), the navigation graph node on that side gets eliminated …
=> Remove graph nodes from locked-off hallways when searching for paths

pyrobosim/pyrobosim/gui/main.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py, pyrobosim_ros/test/test_ros_interface.py
This PR cleanly shuts down the ROS interface node by bringing down the ROS executor as part of the GUI's close event, and handling some other logic a bit.
Closes #252
=> Cleanly shutdown ROS interface node

pyrobosim/pyrobosim/utils/motion.py, pyrobosim/test/core/test_robot.py, pyrobosim/test/utils/test_motion_utils.py, pyrobosim_msgs/msg/Path.msg, pyrobosim_ros/pyrobosim_ros/ros_conversions.py, pyrobosim_ros/test/test_ros_conversions.py
This was briefly brought up at a meeting earlier, and I agree it's generally good to have!
=> Include navigation path length in ROS message

pyrobosim/pyrobosim/gui/world_canvas.py
This was a bug in which some conditions in the GUI versions of actions were still returning a boolean instead of the `ExecutionStatus`... and in one case with pick, was returning `None`.
=> Consistently return execution status in GUI callbacks

pyrobosim_msgs/msg/RobotState.msg, pyrobosim_ros/pyrobosim_ros/ros_interface.py
It's generally a good idea to have timestamped robot state messages if they are being streamed via topic.
=> Add header to RobotState message

pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/gui/world_canvas.py
Turns out that updating the robot state did not take effect after using the individual `/<robot_name>/follow_path` action, since these updates were tied to the completion of the execution of the abstract action rather than at the end of `Robot.follow_path()`.
=> Consistently update robot state in GUI after path following

pyrobosim/pyrobosim/core/world.py, pyrobosim/test/core/test_hallway.py, pyrobosim/test/core/test_locations.py
If a robot tries to open a location and it's already open, we were previously counting this as a failure. Instead, we could consider this a trivial action and still count it as a success.
Same for close, lock, and unlock operations.
=> Count open, close, lock, and unlock trivial operations as success

pyrobosim/pyrobosim/core/dynamics.py, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/gui/world_canvas.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py
This PR runs the `World.get_location_from_pose()` function consistently when a robot's pose is changed, but also optimizes it to favor the robot's previous location.
Empirically, I could notice a ~5-10x speedup assuming the robot isn't teleporting all the time.
=> Use `get_location_from_pose` function consistently and optimize it to check the previous location

pyrobosim/pyrobosim/core/hallway.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/utils/knowledge.py, pyrobosim/test/core/test_hallway.py, pyrobosim/test/core/test_world.py, pyrobosim/test/utils/test_knowledge_utils.py
If a hallway is created from, e.g., `kitchen` to `bathroom`, it is automatically named `hall_kitchen_bathroom` and can only be looked up with that name. But it is mildly annoying to have to get the order right.
This PR adds a "reversed name", so `hall_bathroom_kitchen` also works in lookups.
@dcconner FYI
=> Allow looking up hallways by reversed name

pyrobosim/pyrobosim/core/hallway.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/test/core/test_hallway.py, pyrobosim/test/core/test_locations.py, pyrobosim/test/core/test_objects.py, pyrobosim/test/core/test_robot.py, pyrobosim/test/core/test_room.py, pyrobosim/test/utils/test_knowledge_utils.py
This PR enforces consistency in hallway naming by allowing users to specify an explicit name for their hallway. Otherwise, the `World.add_hallway()` method will choose a name such as `hall_kitchen_bathroom`.
Moreover, this allows multiple hallways connecting two rooms to be specified, as the naming convention will follow:
* `hall_bathroom_kitchen` (always alphabetized, starts with no mangle for backward compatibility)
* `hall_bathroom_kitchen_1` (starts mangle at 1)
* `hall_bathroom_kitchen_2`
* ...
It also fixes a few extra things along the way:
* The `num_hallways` counter was not being properly decremented when a hallway was removed
* Added duplicate name checking logic to `add_room`, `add_hallway`, `add_location`, and `add_object` methods, including unit tests.
Closes …
=> Allow multiple hallways connecting two rooms and check for duplicate names in world add methods

pyrobosim/pyrobosim/manipulation/grasping.py
Found an issue in which the ROS versions of matplotlib (installed via `rosdep`/`apt`) can conflict with `pip` installed versions -- specifically for the `mpl_toolkits.mplot3d.axes3d` module.
```
/usr/local/lib/python3.12/dist-packages/matplotlib/projections/__init__.py:63: 
UserWarning: Unable to import Axes3D. 
This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package).
As a result, the 3D projection is not available.
...
File "/delib_ws/build/pyrobosim/pyrobosim/manipulation/grasping.py", line 9, in <module>
from mpl_toolkits.mplot3d import Axes3D
File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/__init__.py", line 1, in <module>
from .axes3d import Axes3D
File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/axes3d.py", …
```
=> Import matplotlib 3D tools in the bodies of grasp plotting functions

docs/source/index.rst
Adds https://github.com/ros-wg-delib/roscon24-workshop to the usage examples docs section.
=> Add ROSCon 2024 workshop to usage examples

pyrobosim/pyrobosim/gui/world_canvas.py
Attempts to mitigate UI syncing issues when sending several actions in the ROS backend.
=> Enable interactive mode in GUI MatPlotLib canvas

docs/source/usage/robot_actions.rst, pyrobosim/test/core/test_robot.py
The actions docs include a `TaskAction`
```python
TaskAction("place", "object", "apple")
```
I think this is a typo and should be
```python
TaskAction("place", object="apple")
```
(except the robot is named "object" I guess 🙃 )
=> Fix typo in actions documentation

pyrobosim/pyrobosim/core/world.py
This PR allows for sampling object poses if its location is updated in `World.update_object()`.
Since the sampling logic was already present in `World.add_object()`, it also factors it out into a reusable function.
Closes #286
=> Sample object poses in `World.update_object`

pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/gui/main.py
This PR fixes plan cancellation logic so the robot is not stuck canceling.
It also switches the external calls to `PyRoboSimMainWindow.update_button_state()` to happen using signals, to be better behaved.
=> Fix plan cancellation logic

pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/gui/action_runners.py, pyrobosim/pyrobosim/gui/world_canvas.py
This PR configures all robot actions started from the GUI to be `QRunnable` objects run from a `QThreadPool`, as was already done for the "navigate" action.
This primarily makes it so that delayed actions are non-blocking to the GUI and don't freeze it up over long delays... plus you can switch to another robot and do other tasks during delayed actions.
Closes https://github.com/sea-bass/pyrobosim/issues/289
=> Run all robot actions in GUI in separate threads

pyrobosim/pyrobosim/core/world.py
This PR allows room and hallway walls to collide when adding them to a world, so long as the interiors are not overlapping.
Closes #293
=> Allow collisions between walls in rooms and hallways

docs/source/yaml/world_schema.rst, pyrobosim/pyrobosim/core/yaml_utils.py, pyrobosim/pyrobosim/data/pddlstream_simple_world.yaml, pyrobosim/pyrobosim/data/test_world.yaml, pyrobosim/pyrobosim/data/test_world_multirobot.yaml, pyrobosim/pyrobosim/utils/pose.py, pyrobosim/test/system/test_system_world.yaml, pyrobosim/test/utils/test_pose_utils.py
This PR allows YAML specifications of poses, such as
```yaml
pose:
position:
x: 1.0
y: 2.0
rotation_eul:
yaw: 1.57
```
or
```yaml
pose:
position:
x: 1.0
y: 2.0
rotation_quat:
w: 0.7071
x: 0.0
y: 0.0
z: -0.7071
```
This is intended to be the default specification going forward, but keeping the old one for backward compatibility.
It also adds a `to_dict()` method for poses, which will be instrumental to serializing worlds to YAML in follow-on PRs.
=> Allow specifying poses as YAML in world files

pyrobosim/examples/demo.py, pyrobosim/pyrobosim/core/room.py, pyrobosim/pyrobosim/data/test_world.yaml, pyrobosim/pyrobosim/data/test_world_multirobot.yaml, pyrobosim/pyrobosim/utils/general.py, pyrobosim/test/core/test_room.py, pyrobosim/test/core/test_yaml_utils.py, pyrobosim/test/utils/test_general_utils.py
This update allows the `Room` class to accept the color parameter in multiple formats:
- RGB list: `[R, G, B]`
- Named color string (e.g., `"red"`, `"blue"`)
- Hexadecimal string (e.g., `"#0000FF"`)
Unit tests have been added to verify the functionality.
=> Add Support for Multiple Color Formats in Room Class

pyrobosim/examples/demo.py, pyrobosim/pyrobosim/core/hallway.py, pyrobosim/pyrobosim/core/locations.py, pyrobosim/pyrobosim/core/objects.py, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/room.py, pyrobosim/pyrobosim/data/test_world.yaml, pyrobosim/pyrobosim/data/test_world_multirobot.yaml, pyrobosim/pyrobosim/utils/general.py, pyrobosim/test/core/test_room.py, pyrobosim/test/core/test_yaml_utils.py, pyrobosim/test/utils/test_general_utils.py
This update allows the `Hallway`, `Robot`, `Object` and `Location` class to accept the color parameter in multiple formats:
- RGB list: [R, G, B]
- Named color string (e.g., "red", "blue")
- Hexadecimal string (e.g., "#0000FF")
Unit tests have been modified wherever needed.
=> Add Support for Multiple Color Formats in Hallway, Robot, Object and Location class.

.dockerignore, docker-compose.yaml, docker/Dockerfile
We're now mounting the `docs` folder and installing the pip requirements for building docs.
I also added a `docs` service so you can do `docker compose run docs` to generate the documentation.
FYI @kumar-sanjeeev
=> Allow building docs in Docker containers

docs/source/yaml/location_schema.rst, docs/source/yaml/object_schema.rst, docs/source/yaml/world_schema.rst, pyrobosim/examples/demo.py, pyrobosim/pyrobosim/data/pddlstream_simple_world.yaml, pyrobosim/pyrobosim/data/test_world.yaml, pyrobosim/pyrobosim/data/test_world_multirobot.yaml, pyrobosim/pyrobosim/utils/pose.py, pyrobosim/test/utils/test_pose_utils.py
This PR added the functionality to specify Pose angles in degrees also.
-  `angle_units` parameter is introduced to specify the units of the angle.
-  if `angle_units` is not specified, the default unit is set to `radians`.
-  modified demo script to verify the correct behavior when `angle_units` is set to `degrees`.
Unit Tests added to verify and test new functionality
=> Add support to allow pose angles in degrees

pyrobosim/pyrobosim/navigation/a_star.py
When initializing `AStarPlanner` the GUI throws the following error:
```
Traceback (most recent call last):
File "/home/robin/Desktop/px4-ros2-env/install/auto_apms_simulation/lib/auto_apms_simulation/world.py", line 41, in <module>
main()
File "/home/robin/Desktop/px4-ros2-env/install/auto_apms_simulation/lib/auto_apms_simulation/world.py", line 37, in main
start_gui(node.world)
File "/home/robin/Desktop/px4-ros2-env/install/auto_apms_simulation/local/lib/python3.10/dist-packages/pyrobosim/gui/main.py", line 23, in start_gui
app = PyRoboSimGUI(world, sys.argv)
File "/home/robin/Desktop/px4-ros2-env/install/auto_apms_simulation/local/lib/python3.10/dist-packages/pyrobosim/gui/main.py", line 44, in __init__
self.main_window = PyRoboSimMainWindow(self.world, show)
File …
```
=> Add latest path reset to AStarPlanner

pyrobosim/pyrobosim/utils/knowledge.py
When picking objects with multiple robots in a world, it is likely, that some are currently carried and do not reside on locations anymore. Since `Robot` doesn't have a `parent` attribute, an error is raised when checking each object's location.
```
[world.py-1] [ERROR] [1734861471.897019297] [pyrobosim]: Error raised in execute callback: 'Robot' object has no attribute 'parent'
[world.py-1] Traceback (most recent call last):
[world.py-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/action/server.py", line 333, in _execute_goal
[world.py-1]     execute_result = await await_or_execute(execute_callback, goal_handle)
[world.py-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
[world.py-1]     return …
```
=> Fix error when resolving possible objects to pick while some are carried by other robots

pyrobosim/pyrobosim/core/robot.py, pyrobosim/test/core/test_robot.py
Currently, the `Robot.cancel_actions()` method will wait for the `Robot.canceling_execution` flag becoming `False` indefinitely when `Robot.execute_action()` fails to set `self.executing_action = False` before `Robot.cancel_actions()` (e.g. running in a separate thread) checks that in the if statement.
https://github.com/sea-bass/pyrobosim/blob/c36d1989ff27b1d66b738ef3dec9bfd336bbcbf4/pyrobosim/pyrobosim/core/robot.py#L955-L958
This is because `Robot.canceling_execution` is only updated by `Robot.execute_plan()` and not `Robot.execute_action()`.
In this PR I suggest an alternative function design for canceling actions as well as plans using `Robot.cancel_actions()` that ensures it will complete when the respective execution callback returns.
=> Make sure robot.cancel_actions will return

docs/source/yaml/world_schema.rst, pyrobosim/examples/demo.py, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/room.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/core/yaml_utils.py, pyrobosim/pyrobosim/data/pddlstream_simple_world.yaml, pyrobosim/pyrobosim/data/test_world.yaml, pyrobosim/pyrobosim/data/test_world_multirobot.yaml, pyrobosim/pyrobosim/utils/pose.py, pyrobosim/test/core/test_room.py, pyrobosim/test/core/test_yaml_utils.py, pyrobosim/test/system/test_system_world.yaml, pyrobosim_ros/examples/demo.py
This PR implements a mechanism to express poses relative to other entities.
Closes https://github.com/sea-bass/pyrobosim/issues/298
=> Allow specifying relative poses

docs/source/index.rst
I'd like to add my software to the usage examples since I use pyrobosim for demonstrating its use case. I also plan to extend the interface to pyrobosim to allow users to easily prototype the behaviors they create using AutoAPMS without having to set up the workspace themselves. Pyrobosim is the default simulation environment and comes out of the box when installing AutoAPMS.
=> Add AutoAPMS to usage examples

pyrobosim/pyrobosim/core/hallway.py, pyrobosim/pyrobosim/utils/polygon.py, pyrobosim/test/utils/test_polygon_utils.py
This PR handles a few edge cases due to infinitely thin hallways in two dimensions, since Shapely doesn't seem to handle them gracefully:
1. No clearance between the walls of the two neighboring rooms (requires checking polygon emptiness before inflating)
2. Hallway half-width smaller than the world inflation radius (requires checking these values and returning an empty Polygon)
I think in both cases, I've narrowed it down to this: https://github.com/shapely/shapely/pull/2214
Closes #325
=> Handle empty polygons in inflate_polygon

pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/core/yaml_utils.py, pyrobosim/pyrobosim/data/example_location_data_accessories.yaml, pyrobosim/pyrobosim/gui/main.py, pyrobosim/test/core/test_world.py, pyrobosim_msgs/CMakeLists.txt, pyrobosim_msgs/srv/ResetWorld.srv, pyrobosim_ros/pyrobosim_ros/ros_interface.py
This PR takes over from #321 to refactor world resetting so that it's usable in all modes of operation: standalone, through ROS service, and through the GUI.
Closes #319
=> Refactor world resetting to allow standalone use and ROS service

pyrobosim_ros/pyrobosim_ros/ros_interface.py
Now we can just directly call robot actions and the GUI logic is handled under the hood. I must have missed this.
Closes #337
=> Fix object detection action callback

pyrobosim/pyrobosim/navigation/execution.py
PR ensures the `message` variable is defined before being passed to the `logger` and `ExecutionResult`. This prevents runtime errors due to undefined variable usage on lines 100 and 109.
=> Fix bug in logger messages

pyrobosim/pyrobosim/data/roscon_2024_location_data.yaml, pyrobosim/pyrobosim/data/roscon_2024_object_data.yaml, pyrobosim/pyrobosim/data/roscon_2024_workshop_world.yaml
This adds a world "snapshotted" from the ROSCon 2024 workshop: https://github.com/ros-wg-delib/roscon24-workshop
```
python pyrobosim/examples/demo.py --world-file roscon_2024_workshop_world.yaml
```
=> Add ROSCon 2024 workshop worlds

pyrobosim/pyrobosim/core/hallway.py, pyrobosim/pyrobosim/core/locations.py, pyrobosim/pyrobosim/core/objects.py, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/room.py, pyrobosim/pyrobosim/core/types.py, pyrobosim/test/utils/test_knowledge_utils.py, pyrobosim_ros/examples/demo_pddl_planner.py
I found an error in the ROS PDDL demo that was catching an exception but still proceeding with a task plan.
In un-catching this exception, I found the bug was another post-type annotation refactor issue. In this case, the `Room` class did not have a `parent` attribute. So I've made all `Entity` subclasses actually use their parent class' constructor, which fixes the underlying issue in the demo.
=> Use common Entity parent class constructor

docs/python_docs_requirements.txt, docs/source/conf.py
Adds the 'sphinx-copybutton' extension so users can easily copy terminal commands from the docs. A simple, nice-to-have improvement to the documentation!
=> Enable copy buttons on command blocks in docs

setup/setup_pyrobosim.bash
The setup script now automatically detects the ROS workspace path based on the script’s location. This avoids having to manually edit the path at the top. If the workspace isn’t found, a clear message is shown.
Hope this one makes it in just in time for the next release too! 😁
=> Auto-detect ROS workspace in setup script

pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/navigation/a_star.py, pyrobosim/pyrobosim/navigation/prm.py, pyrobosim/pyrobosim/navigation/rrt.py, pyrobosim/pyrobosim/navigation/world_graph.py, pyrobosim/setup.py, test/python_test_requirements.txt
This PR has a few fixes I found while giving things a tests.
* PRM and RRT was not being `reset()` at the right time, so when you started the multirobot world, the planners did not work unless you reset them manually. Moved the calls to `reset()` for planners in the `World.add_robot()` method to fix this.
* `setuptools` needed to be pinned to below 80.0.0 due to https://github.com/pypa/setuptools/issues/4971 -- this was preventing `colcon build` with `--symlink-install`.
* Removed a seemingly useless `tests_require` line that was giving me a build warning.
=> Fix planner initialization after partial hallway observability PR

pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/core/yaml_utils.py, pyrobosim/pyrobosim/utils/world_collision.py
When `location: "some_loc_name"` is not specified in a world YAML file for a robot, there were a few small bugs that prevented the robot from spawning correctly.
=> Fix robot spawning when location is not set in YAML

pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/core/yaml_utils.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py
Done purely to mitigate the effects of this bug: https://github.com/ros2/rclpy/issues/1206
=> Do not remove and re-add ROS interfaces on world reset

pyrobosim/pyrobosim/core/types.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/core/yaml_utils.py, pyrobosim/test/core/test_world.py, pyrobosim/test/core/test_yaml_utils.py, pyrobosim_msgs/srv/ResetWorld.srv, pyrobosim_ros/pyrobosim_ros/ros_interface.py
Closes #380 
This additionally fixes an issue in which the world metadata kept ballooning in size on subsequent world resets, causing exponential slowdowns. This will be a very important fix to have right away.
=> Allow resetting worlds with a specific RNG seed

pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/core/yaml_utils.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py
While https://github.com/sea-bass/pyrobosim/pull/382 helps real with ROS middleware issues, it did have an edge case if you added any new robots at runtime, as its ROS interfaces would not get cleaned up on reset even if that robot did not exist after the reset!
This PR thereby checks if there are any lingering ROS interfaces that do not correspond to currently existing robot, and does delete those.
As a bonus, I also found a one-line change that optimizes the rendering speed on world resets. Thank goodness.
=> Cleanup stale ROS interfaces when resetting world

.github/workflows/tests.yml, docs/source/yaml/world_schema.rst, pyrobosim/examples/demo.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/core/yaml_utils.py, pyrobosim/pyrobosim/data/test_world_multirobot.yaml, pyrobosim/pyrobosim/utils/knowledge.py, pyrobosim/test/core/test_yaml_utils.py, pyrobosim_ros/examples/demo.py
This PR expands object and robot spawning functionality in 2 ways:
* Allows specifying a list of entities or entity names, e.g., `["table0", "my_desk"]`
* Allows specifying location categories as well, e.g., `["table", "desk"]`, or even full queries like `"kitchen table"`!
And a combination of them all, of course!
Closes #390
=> Allow specifying lists of locations or location queries for robot and object spawning
