sea-bass/pyrobosim

.dockerignore, .github/workflows/actions.yml, .gitignore, docker/Dockerfile.foxy, docker/Dockerfile.humble, docker/entrypoint_foxy.sh, docker/entrypoint_humble.sh, docker/run_docker.bash, docker/test_docker.bash, docs/source/conf.py, docs/source/setup.rst, setup/generate_docs.bash, setup/setup_pddlstream.bash, setup/source_pyrobosim.bash, test/run_tests.bash, test/test_dependencies.py
This is the first step towards getting the [PDDLStream](https://github.com/caelan/pddlstream) task and motion planner integrated (https://github.com/sea-bass/pyrobosim/issues/2).
This PR just gets all the dependencies squared away, to the point that the setup scripts, Docker containers, etc. automate the installation/setup of PDDLStream. Sadly this increases the test setup times by about 5 minutes, but it's still fairly quick in the grand scheme of things.
I also did some fixes along the way to setup/sourcing the environment and tightening up the unit test workflow. More PRs will come that do the actual Python code and task and motion planning.
=> Initial PDDLStream Integration 

docs/source/yaml/location_schema.rst, docs/source/yaml/world_schema.rst, pyrobosim/examples/demo.py, pyrobosim/pyrobosim/core/gazebo.py, pyrobosim/pyrobosim/core/locations.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/data/pddlstream_simple_world.yaml, pyrobosim/pyrobosim/data/test_world.yaml, pyrobosim/pyrobosim/data/test_world_multirobot.yaml, pyrobosim/pyrobosim/gui/world_canvas.py, pyrobosim/pyrobosim/navigation/execution.py, pyrobosim/pyrobosim/navigation/trajectory.py, pyrobosim/pyrobosim/utils/general.py, pyrobosim/pyrobosim/utils/motion.py, pyrobosim/pyrobosim/utils/polygon.py, pyrobosim/pyrobosim/utils/pose.py, pyrobosim/pyrobosim/utils/ros_conversions.py, test/planning/test_pddlstream_manip.py, test/planning/test_pddlstream_nav.py, test/world_model/test_get_entities.py
... with the goal of using this to plan grasps, eventually.
So far I've only tested this with the basic demo, `python3 examples/demo.py`
=> Convert Pose class to full 3D

docs/source/concepts.rst, docs/source/usage/geometry_conventions.rst, docs/source/usage/index.rst
=> Document reference frame and rotation conventions.

pyrobosim/pyrobosim/core/hallway.py, pyrobosim/pyrobosim/core/locations.py, pyrobosim/pyrobosim/core/room.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/navigation/rrt.py
@sea-bass 
I have added some optimizations to speed up some operations
Do you think these will be useful ?
=> Add optimizations

test/test_pyrobosim.py
Seems like the module import unit test is failing on `main`, and in searching for answers I found [this answer](https://stackoverflow.com/questions/30483246/how-can-i-check-if-a-module-has-been-imported), which I think is worth using.
=> Fix pyrobosim module import test

CONTRIBUTING.md, README.md, docs/source/index.rst, setup/generate_docs.bash
=> Add contributor guide

.github/workflows/tests.yml, docker-compose.yaml, docker/Dockerfile, docs/source/yaml/world_schema.rst, pyrobosim/examples/demo.py, pyrobosim/examples/demo_astar.py, pyrobosim/examples/demo_pddl.py, pyrobosim/examples/demo_prm.py, pyrobosim/examples/demo_rrt.py, pyrobosim/examples/test_world.py, pyrobosim/pyrobosim/core/yaml_utils.py, pyrobosim/pyrobosim/data/pddlstream_simple_world.yaml, pyrobosim/pyrobosim/data/test_world.yaml, pyrobosim/pyrobosim/data/test_world_multirobot.yaml, pyrobosim/pyrobosim/gui/main.py, pyrobosim/pyrobosim/gui/world_canvas.py, pyrobosim_ros/examples/demo.py, pyrobosim_ros/examples/demo_pddl_world.py, pytest.ini, setup/create_python_env.bash, test/navigation/test_rrt.py, test/run_tests.bash, test/system/test_system.py, test/system/test_system_world.yaml
One small step towards addressing the mega-issue in https://github.com/sea-bass/pyrobosim/issues/86.
This PR specifically adds tests that instantiate a pyrobosim GUI in headless mode and test the navigate, pick, and place button callbacks to see if the robot behaves as expected.
Effectively, these new tests automate the task of opening up the main `demo.py` and testing that the robot does what it's supposed to.
=> Add system tests for pyrobosim UI

pyrobosim/pyrobosim/gui/main.py, pyrobosim/pyrobosim/utils/knowledge.py
I conducted a quick book club session at PickNik today and, of course, there were bugs.
The ones I wrote down should be fixed here, but what we really need is https://github.com/sea-bass/pyrobosim/issues/99 to be implemented well.
List of bugs that were fixed:
* Entering a garbage value in the object query should fail, not return a random object
* If an object query resolves to `None`, the tool shouldn't crash
* Dealt with other issues that cropped up when I fixed the 2 above :)
=> Fix entity resolution bugs from PickNik book club session

pyrobosim/pyrobosim/navigation/a_star.py, pyrobosim/pyrobosim/navigation/prm.py, pyrobosim/pyrobosim/navigation/rrt.py, pyrobosim/pyrobosim/navigation/world_graph.py, pyrobosim/pyrobosim/utils/search_graph.py
The graph based A-Star did not have any use on its own and hence did not make sense for it to exist as a selectable implementation.
It has been moved into the `SearchGraph` to provide search functionality as part of the the graph instead
=> Move graph based A* into `SearchGraph`

.pre-commit-config.yaml, .readthedocs.yaml, docker-compose.yaml, pyrobosim/pyrobosim/core/objects.py, pyrobosim/pyrobosim/navigation/planner_base.py, pyrobosim/pyrobosim/planning/__init__.py, pyrobosim_ros/launch/demo.launch.py, pyrobosim_ros/launch/demo_commands.launch.py, pyrobosim_ros/launch/demo_commands_multirobot.launch.py, pyrobosim_ros/launch/demo_pddl.launch.py
Updated existing pre-commit config, then added codespell, yamllint, and markdown link checker.
=> Update pre-commit configuration

pyrobosim_ros/examples/demo_pddl_planner.py
Fixes exception thrown in https://github.com/sea-bass/pyrobosim/issues/116
=> Do not publish task plan in ROS example if the plan is None

pyrobosim/examples/demo_astar.py, pyrobosim/examples/demo_prm.py, pyrobosim/examples/demo_rrt.py, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/gui/world_canvas.py, pyrobosim_ros/examples/demo_commands.py
Fixes  #118
I ran all ROS demos, all of them work without any errors.
=> Remove reference to world planner in `Robot` class

pyrobosim/pyrobosim/utils/pose.py, test/utils/test_pose_utils.py
Adds unit tests for the `pose.py` file, and fixes a couple of small things found while testing.
Closes https://github.com/sea-bass/pyrobosim/issues/97.
=> Add Pose unit tests

pyrobosim/pyrobosim/navigation/occupancy_grid.py, pyrobosim/pyrobosim/navigation/trajectory.py, pyrobosim/pyrobosim/utils/motion.py, test/navigation/test_trajectory.py, test/utils/test_motion_utils.py
This PR adds unit tests for path and trajectory utilities.
Closes https://github.com/sea-bass/pyrobosim/issues/100
Closes https://github.com/sea-bass/pyrobosim/issues/101
=> Unit tests for path and trajectory utilities

pyrobosim/examples/demo.py, pyrobosim/examples/demo_astar.py, pyrobosim/examples/demo_world_save.py, pyrobosim/pyrobosim/core/yaml_utils.py, pyrobosim/pyrobosim/navigation/occupancy_grid.py, pyrobosim/pyrobosim/navigation/world_graph.py, pyrobosim/pyrobosim/utils/motion.py, test/navigation/test_astar.py, test/navigation/test_occupancy_grid.py
This PR adds unit tests for the occupancy grid functionality and also resolves a few issues / naming conventions found along the way.
Closes https://github.com/sea-bass/pyrobosim/issues/102
=> Unit tests for occupancy grid utilities

pyrobosim/pyrobosim/core/yaml_utils.py, test/core/test_yaml_utils.py
Closes https://github.com/sea-bass/pyrobosim/issues/95
=> Add unit tests for world YAML loading utilities

.github/workflows/tests.yml, .readthedocs.yaml, CONTRIBUTING.md, docs/python_docs_requirements.txt, docs/source/conf.py, setup/generate_docs.bash, test/run_tests.bash
Closes https://github.com/sea-bass/pyrobosim/issues/149
=> Show coverage in PRs + fix ReadTheDocs build

.github/workflows/tests.yml
Buh Bam: https://github.com/sea-bass/pyrobosim/pull/158/checks
I've never seen such a green pipeline.
=> Skip coverage comment for PRs from forks

docs/source/conf.py
Noticed this when I was pulling up the docs and seeing "0.0.0" as the version.
=> Set package version in Sphinx configuration

pyrobosim_ros/pyrobosim_ros/ros_interface.py, setup/create_python_env.bash, setup/generate_docs.bash, setup/source_pyrobosim.bash
Missed some docstring updates in #173...
I also took the liberty of cleaning up some scripts by adding print statements and making small tweaks.
=> Fix ros_interface.py constructor docstring and clean up scripts

pyrobosim/pyrobosim/gui/main.py, pyrobosim/pyrobosim/gui/world_canvas.py
I think this finally fixes the annoying `QBasicTimer` error messages!!!
Closes https://github.com/sea-bass/pyrobosim/issues/194
=> Fix GUI threading errors when clicking Navigate button

docs/source/concepts.rst
This work uses PyRoboSim and I want to mention it! https://arxiv.org/abs/2405.02484
=> Add reference to "Hierarchically Decentralized Heterogeneous Multi-Robot Task Allocation System" paper by Kashid and Kumat

.github/workflows/tests.yml
... how was I not already doing this?
=> Run colcon tests in CI

docs/source/concepts.rst, docs/source/index.rst, docs/source/setup.rst, docs/source/usage/basic_usage.rst, docs/source/usage/index.rst, docs/source/usage/multirobot.rst, docs/source/usage/path_planners.rst, docs/source/usage/robot_actions.rst, docs/source/usage/robot_dynamics.rst, docs/source/usage/tamp.rst, docs/source/yaml/index.rst, docs/source/yaml/location_schema.rst, docs/source/yaml/object_schema.rst, docs/source/yaml/world_schema.rst
It had been a while, so I read through all the docs and made changes here and there...
=> Go through docs after latest changes

pyrobosim/pyrobosim/planning/actions.py, test/planning/test_task_objects.py, test/utils/test_motion_utils.py
This is a silly PR that tests the printing capabilities of the plan objects... mostly just to improve coverage, but also I did find some small issues to fix.
Closes #189
=> Add test coverage to plan printing

pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/gui/main.py, pyrobosim/pyrobosim/gui/world_canvas.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py
I am once again trying to get rid of cryptic QT error messages...
Also found a bug in the ROS interface with dynamics timers being created more than necessary. Woops, sneaking that one in :)
=> Use signals and slots in GUI display methods

pyrobosim_ros/pyrobosim_ros/ros_interface.py
This PR fixes the case where an action is aborted due to an invalid robot name or currently executing action(s).
Somehow I didn't know we still had to return a result.
Thanks for reporting this @dcconner!
=> Fix ROS 2 action abort paths

pyrobosim/pyrobosim/core/robot.py, pyrobosim_msgs/CMakeLists.txt, pyrobosim_msgs/action/DetectObjects.action, pyrobosim_ros/pyrobosim_ros/ros_interface.py, pyrobosim_ros/test/test_ros_interface.py
This PR adds specialized ROS action servers for robots to perform object detection.
To call this, for example:
```
ros2 action send_goal /robot/detect_objects pyrobosim_msgs/action/DetectObjects "{}"
ros2 action send_goal /robot/detect_objects pyrobosim_msgs/action/DetectObjects "{target_object: water}"
```
=> Add specialized ROS action for object detection

pyrobosim_msgs/CMakeLists.txt, pyrobosim_msgs/msg/HallwayState.msg, pyrobosim_msgs/msg/WorldState.msg, pyrobosim_ros/pyrobosim_ros/ros_interface.py, pyrobosim_ros/test/test_ros_interface.py
This was missing and it's probably going to be useful for the ROSCon 2024 workshop...
=> Include hallway state in world state ROS message

pyrobosim/pyrobosim/core/hallway.py
Found a small issue with collision checking when hallways are closed.
=> Fix collision checking with closed hallways

pyrobosim/pyrobosim/core/world.py, pyrobosim/pyrobosim/core/yaml_utils.py, pyrobosim/pyrobosim/gui/main.py, pyrobosim/pyrobosim/gui/world_canvas.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py
This only currently works if the world was loaded from a YAML file. Otherwise, we need to actually store a full state.
... maybe in future we can make a function that serializes a world to file which should help.
=> Add world reset UI button

pyrobosim/pyrobosim/gui/main.py, pyrobosim/pyrobosim/gui/world_canvas.py, pyrobosim/pyrobosim/navigation/execution.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py
Thanks for the assist, @dcconner!
Tested on the workshop code and it works great.
=> Fix path following cancelation logic

pyrobosim/pyrobosim/core/world.py, pyrobosim/test/core/test_world.py
=> Fix object spawn getters

setup/setup_pyrobosim.bash
I was testing something with Jazzy and realized this wasn't being done!
=> Run `rosdep install` in setup script

pyrobosim/pyrobosim/core/locations.py, pyrobosim/pyrobosim/core/yaml_utils.py, pyrobosim/pyrobosim/data/example_location_data.yaml
Found some bugs when testing -- of course I find them after the release 3.2.0 was already done, haha.
=> Fix bugs in pose setting for locations

pyrobosim_ros/pyrobosim_ros/ros_interface.py
This PR ensures that the PyRoboSim ROS interface sets the goal status correctly if an action is canceled.
=> Set action goals to canceled status correctly in ROS interface

docs/source/index.rst
Found this usage example on LinkedIn!
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5097309
=> Add Collaborative Large Language Models for Task Allocation in Construction Robots usage example

pyrobosim/setup.py
I don't even remember what it was that required pinning NumPy in the first place...
=> Unpin NumPy version

pyrobosim/pyrobosim/core/robot.py
=> Fix bug in robot grasp selection logic

test/python_test_requirements.txt
TBD if colcon test succeeds, hope it does as this is addresses a vulnerability
=> Update setuptools version

.github/workflows/tests.yml, docs/source/setup.rst, setup/setup_pyrobosim.bash
Merging as soon as the ROS 2 Kilted Docker images are available (assuming tests pass too)
=> Add ROS 2 Kilted to workflows

docs/source/yaml/world_schema.rst, pyrobosim/pyrobosim/core/robot.py, pyrobosim/pyrobosim/data/test_world_multirobot.yaml, pyrobosim/pyrobosim/planning/actions.py, pyrobosim/test/core/test_yaml_utils.py
What the PR title says, but also fixes a few other small issues with the robot serialization (2 missing keys and one tiny sort-of bug with sensor serialization)
Closes #366
=> Serialize robot action execution options to file

pyrobosim_ros/pyrobosim_ros/ros_interface.py
I found this helped with stability...
=> Delete robot ROS interfaces on world reset

pyrobosim_ros/pyrobosim_ros/ros_interface.py
Honestly, I'm just trying to get the RMW to stop crashing on me independent of middleware (DDS and Zenoh alike)
=> Wake ROS executor when interfaces change

pyrobosim_ros/pyrobosim_ros/ros_interface.py
=> Update ROS logger warning syntax

pyrobosim/pyrobosim/core/world.py, pyrobosim/test/core/test_world.py, pyrobosim/test/core/test_yaml_utils.py
=> Allow spawning objects at any location if `parent=None`

pyrobosim/pyrobosim/core/world.py, pyrobosim_ros/pyrobosim_ros/ros_interface.py
Turns out this made the world resetting start climbing up in time as you kept resetting worlds... cool.
=> Do not destroy ROS timers when resetting world
